package goid


// Countries {
//     // "Select a country": "/search",
//     "All Countries":  "/world",
//     "Andorra":  "/andorra",
//     "Angola":  "/angola",
//     "Argentina":  "/argentina",
//     "Armenia":  "/armenia",
//     "Australia":  "/australia",
//     "Austria":  "/austria",
//     "Azerbaijan":  "/azerbaijan",
//     "Bahamas":  "/bahamas",
//     "Bahrain":  "/bahrain",
//     "Bangladesh":  "/bangladesh",
//     "Belarus":  "/belarus",
//     "Belgium":  "/belgium",
//     "Bhutan":  "/bhutan",
//     "Bolivia":  "/bolivia",
//     "Bosnia and Herzegovina":  "/bosnia-herzegovina-1",
//     // "Bosnia and Herzegovina 2":  "/bosnia-herzegovina-2",
//     "Botswana":  "/botswana",
//     "Brazil":  "/brazil",
//     "Brunei Darussalam":  "/brunei-darussalam",
//     "Bulgaria":  "/bulgaria",
//     "Burkina Faso":  "/burkina-faso",
//     "Burundi":  "/burundi",
//     "Cambodia":  "/cambodia",
//     "Cameroon":  "/cameroon",
//     "Canada":  "/canada",
//     "Cape Verde":  "/cape-verde",
//     "Central African Republic":  "/central-african-republic",
//     "Chad":  "/chad",
//     "Chile":  "/chile",
//     "China":  "/china",
//     "Colombia":  "/colombia",
//     "Congo":  "/congo",
//     "Congo DR":  "/congo-dr",
//     "Costa Rica":  "/costa-rica",
//     "Croatia":  "/croatia",
//     "Cuba":  "/cuba",
//     "Cyprus":  "/cyprus",
//     "Czech Republic":  "/czech-republic",
//     "Denmark":  "/denmark",
//     "Djibouti":  "/djibouti",
//     "Dominican Republic":  "/dominican-republic",
//     "Ecuador":  "/ecuador",
//     "Egypt":  "/egypt",
//     "El Salvador":  "/el-salvador",
//     "Estonia":  "/estonia",
//     "Ethiopia":  "/ethiopia",
//     "Faroe Islands":  "/faroeIslands",
//     "Finland":  "/finland",
//     "France":  "/france",
//     "France Departments":  "/france-departments",
//     "France New":  "/france-new",
//     "Georgia":  "/georgia",
//     "Germany":  "/germany",
//     "Greece":  "/greece",
//     "Guatemala":  "/guatemala",
//     "Guinea":  "/guinea",
//     "Haiti":  "/haiti",
//     "Honduras":  "/honduras",
//     "Hong Kong":  "/hong-kong",
//     "Hungary":  "/hungary",
//     "Iceland":  "/iceland",
//     "India":  "/india",
//     "Indonesia":  "/indonesia",
//     "Iran":  "/iran",
//     "Iraq":  "/iraq",
//     "Ireland":  "/ireland",
//     "Israel":  "/israel",
//     "Italy":  "/italy",
//     "Ivory Coast":  "/ivory-coast",
//     "Jamaica":  "/jamaica",
//     "Japan":  "/japan",
//     "Kazakhstan":  "/kazakhstan",
//     "Kenya":  "/kenya",
//     "Kosovo":  "/kosovo",
//     "Kyrgyzstan":  "/kyrgyzstan",
//     "Laos":  "/laos",
//     "Latvia":  "/latvia",
//     "Liechtenstein":  "/liechtenstein",
//     "Lithuania":  "/lithuania",
//     "Luxembourg":  "/luxembourg",
//     "Macedonia":  "/macedonia",
//     "Malaysia":  "/malaysia",
//     "Mali":  "/mali",
//     "Malta":  "/malta",
//     "Mexico":  "/mexico",
//     "Moldova":  "/moldova",
//     "Montenegro":  "/montenegro",
//     "Morocco":  "/morocco",
//     "Mozambique":  "/mozambique",
//     "Myanmar":  "/myanmar",
//     "Namibia":  "/namibia",
//     "Nepal":  "/nepal",
//     "Netherlands":  "/netherlands",
//     "New Zealand":  "/new-zealand",
//     "Nicaragua":  "/nicaragua",
//     "Nigeria":  "/nigeria",
//     "Norway":  "/norway",
//     "Oman":  "/oman",
//     "Pakistan":  "/pakistan",
//     "Palestine":  "/palestine",
//     "Panama":  "/panama",
//     "Paraguay":  "/paraguay",
//     "Peru":  "/peru",
//     "Philippines":  "/philippines",
//     "Poland":  "/poland",
//     "Portugal":  "/portugal",
//     "Portugal Regions":  "/portugal-regions",
//     "Puerto Rico":  "/puerto-rico",
//     "Qatar":  "/qatar",
//     "Romania":  "/romania",
//     "Russia":  "/russia",
//     "Rwanda":  "/rwanda",
//     "San Marino":  "/san-marino",
//     "Saudi Arabia":  "/saudi-arabia",
//     "Serbia":  "/serbia",
//     // "Serbia without Kosovo":  "/serbia-without-kosovo",
//     "Sierra Leone":  "/sierra-leone",
//     "Singapore":  "/singapore",
//     "Slovakia":  "/slovakia",
//     "Slovenia":  "/slovenia",
//     "South Africa":  "/south-africa",
//     // "South Africa 2":  "/south-africa-2",
//     "South Korea":  "/south-korea",
//     "Spain":  "/spain",
//     "Spain provinces":  "/spain-provinces",
//     "Sri Lanka":  "/sri-lanka",
//     "Sudan":  "/sudan",
//     "Sweden":  "/sweden",
//     "Switzerland":  "/switzerland",
//     "Syria":  "/syria",
//     // "Taiwan":  "/taiwan",
//     "Tajikistan":  "/tajikistan",
//     "Thailand":  "/thailand",
//     "Turkey":  "/turkey",
//     "Uganda":  "/uganda",
//     "Ukraine":  "/ukraine",
//     "United Arab Emirates":  "/united-arab-emirates",
//     "United Kingdom":  "/united-kingdom",
//     "United Kingdom counties":  "/united-kingdom-counties",
//     "United States of America": "/usa",
//     "Uruguay":  "/uruguay",
//     "Uzbekistan":  "/uzbekistan",
//     "Venezuela":  "/venezuela",
//     "Vietnam":  "/vietnam",
//     "Vietnam with islands":  "/vietnam-with-islands",
//     "Yemen":  "/yemen",
//     "Zambia":  "/zambia",
//     "Zimbabwe":  "/zimbabwe"

// }